/********************************************************************
* OomonMainFrameDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error OomonMainFrameDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "cint/G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableOomonMainFrameDict();
extern void G__cpp_setup_inheritanceOomonMainFrameDict();
extern void G__cpp_setup_typetableOomonMainFrameDict();
extern void G__cpp_setup_memvarOomonMainFrameDict();
extern void G__cpp_setup_globalOomonMainFrameDict();
extern void G__cpp_setup_memfuncOomonMainFrameDict();
extern void G__cpp_setup_funcOomonMainFrameDict();
extern void G__set_cpp_environmentOomonMainFrameDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "MMonSelectCanvasFrame.h"
#include "mygblink.h"
#include "MMonMainFrame.h"
#include "KeyStonePad.h"
#include "Handlers.h"

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__OomonMainFrameDictLN_TClass;
extern G__linked_taginfo G__OomonMainFrameDictLN_TBuffer;
extern G__linked_taginfo G__OomonMainFrameDictLN_TMemberInspector;
extern G__linked_taginfo G__OomonMainFrameDictLN_TObject;
extern G__linked_taginfo G__OomonMainFrameDictLN_TList;
extern G__linked_taginfo G__OomonMainFrameDictLN_TString;
extern G__linked_taginfo G__OomonMainFrameDictLN_TQObjSender;
extern G__linked_taginfo G__OomonMainFrameDictLN_Event_t;
extern G__linked_taginfo G__OomonMainFrameDictLN_TGWindow;
extern G__linked_taginfo G__OomonMainFrameDictLN_TGLayoutHints;
extern G__linked_taginfo G__OomonMainFrameDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__OomonMainFrameDictLN_TGVerticalFrame;
extern G__linked_taginfo G__OomonMainFrameDictLN_TGMainFrame;
extern G__linked_taginfo G__OomonMainFrameDictLN_TGPopupMenu;
extern G__linked_taginfo G__OomonMainFrameDictLN_TGButton;
extern G__linked_taginfo G__OomonMainFrameDictLN_TGCheckButton;
extern G__linked_taginfo G__OomonMainFrameDictLN_TGRadioButton;
extern G__linked_taginfo G__OomonMainFrameDictLN_MMonSelectCanvasFrame;
extern G__linked_taginfo G__OomonMainFrameDictLN_TGMenuBar;
extern G__linked_taginfo G__OomonMainFrameDictLN_TGTextEntry;
extern G__linked_taginfo G__OomonMainFrameDictLN_TGNumberEntryField;
extern G__linked_taginfo G__OomonMainFrameDictLN_TGHProgressBar;
extern G__linked_taginfo G__OomonMainFrameDictLN_MMonMainFrame;
extern G__linked_taginfo G__OomonMainFrameDictLN_TPolyLine;
extern G__linked_taginfo G__OomonMainFrameDictLN_TCanvas;
extern G__linked_taginfo G__OomonMainFrameDictLN_KeyStonePad;

/* STUB derived class for protected member access */
