/********************************************************************
* interface/dict_interface.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error interface/dict_interface.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtabledict_interface();
extern void G__cpp_setup_inheritancedict_interface();
extern void G__cpp_setup_typetabledict_interface();
extern void G__cpp_setup_memvardict_interface();
extern void G__cpp_setup_globaldict_interface();
extern void G__cpp_setup_memfuncdict_interface();
extern void G__cpp_setup_funcdict_interface();
extern void G__set_cpp_environmentdict_interface();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "interface/xmlReader.hh"
#include "interface/utils.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__dict_interfaceLN_vectorlEshortcOallocatorlEshortgRsPgR;
extern G__linked_taginfo G__dict_interfaceLN_vectorlEshortcOallocatorlEshortgRsPgRcLcLiterator;
extern G__linked_taginfo G__dict_interfaceLN_reverse_iteratorlEvectorlEshortcOallocatorlEshortgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dict_interfaceLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__dict_interfaceLN_string;
extern G__linked_taginfo G__dict_interfaceLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__dict_interfaceLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dict_interfaceLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__dict_interfaceLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dict_interfaceLN_TFile;
extern G__linked_taginfo G__dict_interfaceLN_tpcXmlConfig;
extern G__linked_taginfo G__dict_interfaceLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__dict_interfaceLN_vectorlEintcOallocatorlEintgRsPgRcLcLiterator;
extern G__linked_taginfo G__dict_interfaceLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dict_interfaceLN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgR;
extern G__linked_taginfo G__dict_interfaceLN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcLcLiterator;
extern G__linked_taginfo G__dict_interfaceLN_reverse_iteratorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dict_interfaceLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR;
extern G__linked_taginfo G__dict_interfaceLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiterator;
extern G__linked_taginfo G__dict_interfaceLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dict_interfaceLN_vectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgR;
extern G__linked_taginfo G__dict_interfaceLN_vectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRcLcLiterator;
extern G__linked_taginfo G__dict_interfaceLN_reverse_iteratorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
typedef vector<short,allocator<short> > G__vectorlEshortcOallocatorlEshortgRsPgR;
typedef vector<int,allocator<int> > G__vectorlEintcOallocatorlEintgRsPgR;
typedef vector<vector<int,allocator<int> >,allocator<vector<int,allocator<int> > > > G__vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgR;
typedef vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > > G__vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR;
typedef vector<vector<short,allocator<short> >,allocator<vector<short,allocator<short> > > > G__vectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgR;
