testcodeTPC: /home/tuchming/data/saclay1_e6430/miniTPC/code/DataWriter/src/acqToRootConverterExe.cc File Reference
acqToRootConverterExe.cc File Reference
#include "interface/xmlReader.hh"
#include "interface/geomManager.hh"
#include "interface/dataDecoder.hh"
#include "interface/tpcDataAnalyzer.hh"
#include "interface/utils.hh"
#include <iostream>
#include <string>
#include <boost/program_options.hpp>
#include <boost/algorithm/string/split.hpp>
#include <boost/algorithm/string.hpp>
#include <boost/filesystem.hpp>
#include <TFile.h>
#include <TCanvas.h>
#include <TH2.h>
#include <TH2Poly.h>
#include <TRint.h>
#include <TTree.h>
Functions
void rootStyle (void)
int main (int nargc, char **argv)
Function Documentation
int main (int nargc, char ** argv)
Definition at line 28 of file acqToRootConverterExe.cc.
References tpcDataDecoder::decodeNextEvent(), tpcDataAnalyzer::drawEvt2D(), tpcXmlConfig::dumpToRootFile(), femGeomManager::dumpToRootFile(), tpcDataDecoder::endOfDataFile(), tpcDataAnalyzer::fillPadsWithMaxCharge(), tpcXmlConfig::load(), rootStyle(), femGeomManager::setElectronicMap(), tpcDataAnalyzer::setGeometry(), and femGeomManager::setGeometryMap().
{
  string xmlFile;
  string dataFile = "unknown";
  string electronicMap = "etc/geom/MapLayoutFile.txt";
  string geometryMap   = "etc/geom/keystonePadGeom.txt";
  int interactive;
  namespace po = boost::program_options;
  po::options_description config("Configuration");
  config.add_options()
    ("help,h" , "help")
    ("xmlFile" , po::value<string>(&xmlFile),"xmlFile" )
    ("elecMap" , po::value<string>(&electronicMap)->default_value("etc/geom/MapLayoutFile.txt"  ),"file with the electronic map layout" )
    ("geomMap" , po::value<string>(&geometryMap  )->default_value("etc/geom/keystonePadGeom.txt"),"file with the geometry map layout" )
    ("f,file"  , po::value<string>(&dataFile)->required(),"data file" )
    ("interactive,i","interactive mode" )
    ;
  po::variables_map vm;
  po::store(po::command_line_parser(nargc, argv).
            options(config).run(), vm);
  po::notify(vm);
  if( vm.count("help") ) {
    cout << config << endl;
    cout << "Usage: ./bin/xmlReaderExe [options]" << endl;
    return 1;
  }
   if(    vm.count("interactive")  ) interactive = 1;
   else                              interactive = 0;
  TRint *theApp   = 0;
  TCanvas *canvas = 0;
  if( interactive ) {
    theApp = new TRint("App", 0, 0);
    canvas = new TCanvas("cMonitoring","cMonitoring",800,600);
    rootStyle();
  }
  /////// get filename and path to work only on filename
  boost::filesystem::path datapath(dataFile);
  boost::filesystem::path datafileDirName  = datapath.parent_path();
  boost::filesystem::path datafileFileName = datapath.filename();
  ////// Decode xml file using input file name
  vector<string> tmpXml;
  boost::split( tmpXml, datafileFileName.string() , boost::is_any_of("."), boost::token_compress_on );
  for( unsigned itmp = 0 ; itmp < tmpXml.size(); itmp++ )
    if( boost::find_first(tmpXml[itmp], "RUN") ) {
      xmlFile = tmpXml[itmp];
      boost::replace_first(xmlFile,"RUN","CFG");
      xmlFile += ".xml";
    }
  xmlFile = datafileDirName.string() + "/" + xmlFile;
  cout << " Opening config xml file = " << xmlFile << endl;
  tpcXmlConfig xmlConfig;
  xmlConfig.load( xmlFile );
  cout << xmlConfig << endl;
  ///// setup geometry
  femGeomManager geomManager;
  geomManager.setElectronicMap(electronicMap);
  geomManager.setGeometryMap(  geometryMap  );
  ////// opening output file
  string outputRootFile = dataFile;
  boost::replace_first(outputRootFile,".acq",".root");
  TFile *fOut = new TFile( outputRootFile.c_str(),"recreate");
  xmlConfig  .dumpToRootFile(fOut);
  geomManager.dumpToRootFile(fOut);
  TTree *t = new TTree("padData","pad data");
  vector<vector<int> > listOfSamples;
  vector<int>          listOfChannels;
  t->Branch("physChannels", &listOfChannels );
  t->Branch("ADCvsTime"   , &listOfSamples );
  ///// prepare data decoder
  tpcDataDecoder decoder(dataFile);
  tpcDataAnalyzer ana;
  ana.setGeometry(geomManager);
  cout << "bobo here " << endl;
  int count=0;
  while( !decoder.endOfDataFile() ) {
    count ++; cout << "bobo decoder " << count << endl;
    vector<tpcPad> pads = decoder.decodeNextEvent();
    cout << "step1 " << endl;
    listOfChannels.erase( listOfChannels.begin(), listOfChannels.end() );
    cout << "step2 " << endl;
   listOfSamples.erase(   listOfSamples.begin(), listOfSamples.end() );
    cout << "step3 " << endl;
   for( unsigned ipad = 0; ipad < pads.size(); ipad++ ) {
      listOfChannels.push_back( pads[ipad].getPhysChannel() );
      listOfSamples.push_back(  pads[ipad].getADCvsTime() );
    }
        cout << "bobo decoder " << count << endl;
    t->Fill();
    //// if monitoring mode - plot max charge
    if( interactive ) {
        canvas->cd();
        ana.fillPadsWithMaxCharge( pads );
        ana.drawEvt2D();
        canvas->Update();
    }
  }
  cout << " ----> Closing output file: " << fOut->GetName() << endl;
  t->Write();
  fOut->Close();
  if( canvas ) delete canvas;
  return 1;
}
void rootStyle (void)
Dzero font
Definition at line 50 of file utils.cc.
                     {
   int font = 132;
   /// Dzero font
   font = 62;
  gROOT->SetStyle("Plain");
  TStyle *fabercStyle= new TStyle("ZFitterFabStyle","ZFitter plots");
  // use plain black on white colors
  fabercStyle->SetFrameBorderMode(0);
  fabercStyle->SetCanvasBorderMode(0);
  fabercStyle->SetPadBorderMode(0);
  fabercStyle->SetPadColor(0);
  fabercStyle->SetCanvasColor(0);
  //fabercStyle->SetTitleColor(0);
  fabercStyle->SetStatColor(0);
  fabercStyle->SetTitleFillColor(0);
  // set the paper & margin sizes
  fabercStyle->SetPaperSize(20,26);
  fabercStyle->SetPadTopMargin(0.08);
  //  fabercStyle->SetPadRightMargin(0.06);
  fabercStyle->SetPadRightMargin(0.15);
  fabercStyle->SetPadBottomMargin(0.13);
  fabercStyle->SetPadLeftMargin(0.12);
  fabercStyle->SetTitleOffset(1.,"y");
  fabercStyle->SetTitleOffset(0.9,"x");
  // use large Times-Roman fonts
  fabercStyle->SetTitleFont(font,"xyz");  // set the all 3 axes title font
  fabercStyle->SetTitleFont(font," ");    // set the pad title font
  fabercStyle->SetTitleSize(0.06,"xyz"); // set the 3 axes title size
  fabercStyle->SetTitleSize(0.06," ");   // set the pad title size
  fabercStyle->SetLabelFont(font,"xyz");
  fabercStyle->SetLabelSize(0.05,"xyz");
  fabercStyle->SetTextFont(42);
  fabercStyle->SetTextSize(0.09);
  fabercStyle->SetStatFont(font);
  // add axis decimal (same for all)
  fabercStyle->SetStripDecimals(0);
  // use bold lines and markers
  fabercStyle->SetMarkerStyle(8);
  fabercStyle->SetMarkerSize(0.8);
  fabercStyle->SetHistLineWidth(2);
  fabercStyle->SetLineWidth(2);
  fabercStyle->SetLineStyleString(2,"[12 12]"); // postscript dashes
  //..Get rid of X error bars
  //fabercStyle->SetErrorX(0.001);
  // do not display any of the standard histogram decorations
  fabercStyle->SetOptTitle(0);
  //  fabercStyle->SetOptStat(111111);
  //  fabercStyle->SetOptStat(1111);
  fabercStyle->SetOptStat(0);
  fabercStyle->SetOptFit(0);
  // fabercStyle->SetPalette(1);
  fabercStyle->SetTitleX(0.2);
  unsigned NRGBs = 5;
  double Red[5]    = { 0.00, 0.2, 0.0, 1.0, 0.70};
  double Green[5]  = { 0.00, 0.8, 0.8, 1.0,  0.00};
  double Blue[5]   = { 0.60, 1.0, 0.1, 0.0,  0.00};
  double Length[5] = { 0.00, 0.42, 0.50, 0.58, 1.00 };
  int nb=50;
  TColor::CreateGradientColorTable(NRGBs, Length, Red, Green, Blue, nb);
  fabercStyle->SetNumberContours(nb);
  // put tick marks on top and RHS of plots
  fabercStyle->SetPadTickX(1);
  fabercStyle->SetPadTickY(1);
  // restore the plain style. Add tick marks and extra stats
  gROOT->SetStyle("ZFitterFabStyle");
}