testcodeTPC: tpcPedestal Class Reference
tpcPedestal Class Reference
#include <tpcPedCalc.hh>
Public Member Functions
tpcPedestal (void)
void calcPedestals (std::string inputPedestalFile, bool drawPed=false)
void dummyPedestals (std::string inputFile, double ped=250, double rms=5)
std::vector< double > getPedestals (void) const
set a default value in case no pedestal file available
std::vector< std::vector
< double > > getPedMean2D (void) const
std::vector< std::vector
< double > > getPedRMS2D (void) const
Private Attributes
std::vector< double > _pedestalsMean1D
std::vector< double > _pedestalsRMS1D
std::vector< std::vector
< double > > _pedestalsMean2D
std::vector< std::vector
< double > > _pedestalsRMS2D
Detailed Description
Definition at line 7 of file tpcPedCalc.hh.
Constructor & Destructor Documentation
tpcPedestal::tpcPedestal (void) [inline]
Definition at line 9 of file tpcPedCalc.hh.
{};
Member Function Documentation
void tpcPedestal::calcPedestals (std::string inputPedestalFile, bool drawPed = false)
Definition at line 15 of file tpcPedCalc.cc.
References femGeomViewer::drawCopyXY(), femGeomManager::initFromRootFile(), femGeomManager::iPad(), femGeomManager::jPad(), femGeomManager::nCol(), femGeomManager::nPad(), femGeomManager::nRow(), femGeomViewer::setBinContent(), femGeomViewer::setMinMax(), and tpcPad::setPad().
Referenced by main().
{
  femGeomManager geo;
  geo.initFromRootFile( inputFile );
  _pedestalsMean1D.resize( geo.nPad(), 0 );
  _pedestalsRMS1D .resize( geo.nPad(), 0 );
  _pedestalsMean2D.resize( geo.nRow(), vector<double>(geo.nCol(),0) );
  _pedestalsRMS2D .resize( geo.nRow(), vector<double>(geo.nCol(),0) );
  TFile *fIn = new TFile( inputFile.c_str(),"read");
  TTree *tree = (TTree*) fIn->Get("padData");
  vector<vector<int> > *listOfSamples(0);
  vector<int>          *listOfChannels(0);
  tree->SetBranchAddress("physChannels", &listOfChannels );
  tree->SetBranchAddress("ADCvsTime"   , &listOfSamples );
  vector<double> mu  ; mu  .resize(geo.nPad(),0);
  vector<double> rms ; rms .resize(geo.nPad(),0);
  vector<int>    nEvt; nEvt.resize(geo.nPad(),0);
  for( int ievt = 0 ; ievt < tree->GetEntries(); ievt++ ) {
    tree->GetEntry(ievt);
    vector<tpcPad> pads;
    for( unsigned ipad = 0; ipad < listOfChannels->size(); ipad++ ) {
      tpcPad p;
      pads.push_back(p);
      pads[pads.size()-1].setPad( (*listOfChannels)[ipad],(*listOfSamples)[ipad] );
    }
    for( unsigned ipad = 0; ipad < pads.size(); ipad++ ) {
      int iCh = pads[ipad].getPhysChannel();
      if( iCh < 0 ) continue;
      double mean = pads[ipad].getMean();
      if( mean > 0.1 ) {
        nEvt[iCh]++;
        mu[iCh]  += mean;
        rms[iCh] += pads[ipad].getRMS();
      }
    }
  }
  for( unsigned ich = 0 ; ich < mu.size(); ich++ ) {
    _pedestalsMean1D[ich] = mu[ich] / nEvt[ich];
    _pedestalsRMS1D[ich]  = rms[ich]/ nEvt[ich];
    _pedestalsMean2D[geo.iPad(ich)][geo.jPad(ich)] = _pedestalsMean1D[ich];
    _pedestalsRMS2D[ geo.iPad(ich)][geo.jPad(ich)] = _pedestalsRMS1D[ ich];
  }
  fIn->Close();
  femGeomViewer pedMeanViewer("hPedestalMean",geo);
  femGeomViewer pedRMSViewer( "hPedestalRMS" ,geo);
  if( drawPed ) {
    for( unsigned ich = 0 ; ich < _pedestalsMean1D.size(); ich++ ) {
      int ipad = geo.iPad(ich);
      int jpad = geo.jPad(ich);
      pedMeanViewer.setBinContent(ipad,jpad,0,_pedestalsMean1D[ich] );
      pedRMSViewer.setBinContent( ipad,jpad,0,_pedestalsRMS1D[ ich] );
    }
    pedMeanViewer.setMinMax(0,500);
    pedRMSViewer .setMinMax(2.5,7.5);
    TCanvas *cMeanCanvas = new TCanvas("cPedestalMean","pedestal mean",900,800);
    TCanvas *cRMSCanvas  = new TCanvas("cPedestalRMS" ,"pedestal RMS" ,900,800);
    cMeanCanvas->cd(); pedMeanViewer.drawCopyXY("colz"); cMeanCanvas->Update();
    cRMSCanvas ->cd(); pedRMSViewer .drawCopyXY("colz"); cRMSCanvas ->Update();
    delete cMeanCanvas;
    delete cRMSCanvas;
  }
}
void tpcPedestal::dummyPedestals (std::string inputFile, double ped = 250, double rms = 5)
Definition at line 95 of file tpcPedCalc.cc.
References femGeomManager::initFromRootFile(), femGeomManager::iPad(), femGeomManager::jPad(), femGeomManager::nCol(), femGeomManager::nPad(), and femGeomManager::nRow().
Referenced by main().
{
  femGeomManager geo;
  geo.initFromRootFile( inputFile );
  _pedestalsMean1D.resize( geo.nPad(), 0 );
  _pedestalsRMS1D .resize( geo.nPad(), 0 );
  _pedestalsMean2D.resize( geo.nRow(), vector<double>(geo.nCol(),0) );
  _pedestalsRMS2D .resize( geo.nRow(), vector<double>(geo.nCol(),0) );
   for( unsigned ich = 0 ; ich < _pedestalsMean1D.size(); ich++ ) {
    _pedestalsMean1D[ich] = ped;
    _pedestalsRMS1D[ich]  = rms;
    _pedestalsMean2D[geo.iPad(ich)][geo.jPad(ich)] = _pedestalsMean1D[ich];
    _pedestalsRMS2D[ geo.iPad(ich)][geo.jPad(ich)] = _pedestalsRMS1D[ ich];
   }
}
std::vector<double> tpcPedestal::getPedestals (void) const [inline]
set a default value in case no pedestal file available
Definition at line 12 of file tpcPedCalc.hh.
References _pedestalsMean1D.
{return _pedestalsMean1D;}
std::vector<std::vector<double> > tpcPedestal::getPedMean2D (void) const [inline]
Definition at line 15 of file tpcPedCalc.hh.
References _pedestalsMean2D.
Referenced by main().
{ return _pedestalsMean2D; }
std::vector<std::vector<double> > tpcPedestal::getPedRMS2D (void) const [inline]
Definition at line 16 of file tpcPedCalc.hh.
References _pedestalsRMS2D.
Referenced by main().
{ return _pedestalsRMS2D; }
Member Data Documentation
std::vector<double> tpcPedestal::_pedestalsMean1D [private]
Definition at line 19 of file tpcPedCalc.hh.
Referenced by getPedestals().
std::vector<std::vector<double> > tpcPedestal::_pedestalsMean2D [private]
Definition at line 22 of file tpcPedCalc.hh.
Referenced by getPedMean2D().
std::vector<double> tpcPedestal::_pedestalsRMS1D [private]
Definition at line 20 of file tpcPedCalc.hh.
std::vector<std::vector<double> > tpcPedestal::_pedestalsRMS2D [private]
Definition at line 23 of file tpcPedCalc.hh.
Referenced by getPedRMS2D().
The documentation for this class was generated from the following files:
/home/tuchming/data/saclay1_e6430/miniTPC/code/DataWriter/interface/tpcPedCalc.hh
/home/tuchming/data/saclay1_e6430/miniTPC/code/DataWriter/src/tpcPedCalc.cc