testcodeTPC: tpcPad Class Reference
tpcPad Class Reference
#include <tpcPadDataFormats.hh>
Public Member Functions
tpcPad (void)
void setPad (int iphysChannel, const std::vector< int > &samples)
int maxCharge (void)
int tAtMax (void)
int getPhysChannel (void) const
std::vector< int > getADCvsTime () const
double getMean () const
double getRMS () const
TH1F * timeSamples (void)
Private Attributes
std::vector< int > _adcVsTime
int _iPhysChannel
int _qMax
int _tMax
Detailed Description
Definition at line 9 of file tpcPadDataFormats.hh.
Constructor & Destructor Documentation
tpcPad::tpcPad (void) [inline]
Definition at line 11 of file tpcPadDataFormats.hh.
:  _iPhysChannel(-1), _qMax(-1), _tMax(-1) {};
Member Function Documentation
std::vector<int> tpcPad::getADCvsTime () const [inline]
Definition at line 19 of file tpcPadDataFormats.hh.
References _adcVsTime.
{ return _adcVsTime; }
double tpcPad::getMean (void) const
Definition at line 38 of file tpcPadDataFormats.cc.
References _adcVsTime, and x.
Referenced by getRMS().
{
  double x = 0;
  int    n = 0;
  for( unsigned is = 0 ; is < _adcVsTime.size(); is++ )
    if( _adcVsTime[is] > 0.01 ) {
      x +=  _adcVsTime[is];
      n++;
    }
  if( n == 0 ) return 0;
  return x / n;
}
int tpcPad::getPhysChannel (void) const [inline]
Definition at line 18 of file tpcPadDataFormats.hh.
References _iPhysChannel.
{return _iPhysChannel;}
double tpcPad::getRMS (void) const
Definition at line 50 of file tpcPadDataFormats.cc.
References _adcVsTime, and getMean().
{
  double mu = getMean();
  double x2 = 0;
  int    n = 0;
  for( unsigned is = 0 ; is < _adcVsTime.size(); is++ )
    if( _adcVsTime[is] > 0.01 ) {
      x2 +=  _adcVsTime[is]*_adcVsTime[is];
      n++;
    }
  if( n <= 1 ) return 0;
  return sqrt((x2 - n*mu*mu) / (n-1));
}
int tpcPad::maxCharge (void)
Definition at line 23 of file tpcPadDataFormats.cc.
References _adcVsTime, _qMax, and _tMax.
Referenced by tAtMax().
{
  if( _qMax < 0 ) {
    std::vector<int>::const_iterator max = max_element(_adcVsTime.begin(), _adcVsTime.end());
    _qMax = *max;
    _tMax = max - _adcVsTime.begin();
  }
  return _qMax;
}
void tpcPad::setPad (int iphysChannel, const std::vector< int > & samples) [inline]
Definition at line 13 of file tpcPadDataFormats.hh.
References _adcVsTime, and _iPhysChannel.
Referenced by tpcPedestal::calcPedestals(), tpcDataDecoder::decodeNextEvent(), and main().
{ _iPhysChannel = iphysChannel; _adcVsTime = samples; }
int tpcPad::tAtMax (void)
Definition at line 32 of file tpcPadDataFormats.cc.
References _tMax, and maxCharge().
                       {
  if( _tMax < 0 ) maxCharge();
  return _tMax;
}
TH1F * tpcPad::timeSamples (void)
Definition at line 8 of file tpcPadDataFormats.cc.
References _adcVsTime.
{
  TH1F *h = new TH1F("hPadSamples","pad samples",_adcVsTime.size(),0.5,_adcVsTime.size()+0.5);
  for( unsigned is = 0 ; is < _adcVsTime.size(); is++ ) {
    h->SetBinContent( is+1, _adcVsTime[is] );
  }
  h->GetXaxis()->SetTitle("time");
  return h;
}
Member Data Documentation
std::vector<int> tpcPad::_adcVsTime [private]
Definition at line 28 of file tpcPadDataFormats.hh.
Referenced by getADCvsTime(), getMean(), getRMS(), maxCharge(), setPad(), and timeSamples().
int tpcPad::_iPhysChannel [private]
Definition at line 29 of file tpcPadDataFormats.hh.
Referenced by getPhysChannel(), and setPad().
int tpcPad::_qMax [private]
Definition at line 30 of file tpcPadDataFormats.hh.
Referenced by maxCharge().
int tpcPad::_tMax [private]
Definition at line 31 of file tpcPadDataFormats.hh.
Referenced by maxCharge(), and tAtMax().
The documentation for this class was generated from the following files:
/home/tuchming/data/saclay1_e6430/miniTPC/code/DataWriter/interface/tpcPadDataFormats.hh
/home/tuchming/data/saclay1_e6430/miniTPC/code/DataWriter/src/tpcPadDataFormats.cc