testcodeTPC: femGeomManager Class Reference
femGeomManager Class Reference
#include <geomManager.hh>
Public Member Functions
femGeomManager (void)
~femGeomManager (void)
femGeomManager (const femGeomManager &geo)
femGeomManager & operator= (const femGeomManager &)
void setElectronicMap (std::string map)
init geometry from flat ascii files
void setGeometryMap (std::string map)
int nPad (void) const
int nRow (void) const
int nCol (void) const
int iPad (int iPhysCh) const
int jPad (int iPhysCh) const
pad row from phys channel
int asic (int iPhysCh) const
pad column from phys channel
int fec (int iPhysCh) const
int padInAsic (int iPhysCh) const
int iPadMin (void) const
int iPadMax (void) const
int jPadMin (void) const
int jPadMax (void) const
double xPad (int i, int j) const
double yPad (int i, int j) const
double xPad (int iPhysCh) const
double yPad (int iPhysCh) const
double xPadCoord (int i, int j, int k) const
double yPadCoord (int i, int j, int k) const
return double[] for root
void dumpToRootFile (TFile *f, const std::string &geoTreeName="femGeomTree")
return double[] for root
void initFromRootFile (std::string rootFileName, const std::string &treeName="femGeomTree")
Private Member Functions
void readElectronic (void)
int readGeometry (void)
Private Attributes
std::string _elecMap
std::string _geomMap
int _iPadMin
int _iPadMax
int _jPadMin
int _jPadMax
std::vector< int > _iPad
std::vector< int > _jPad
std::vector< int > _iAsic
std::vector< int > _iFec
std::vector< int > _iPadInAsic
std::vector< std::vector
< double > > _x0Pad
electronic path
std::vector< std::vector
< double > > _x1Pad
std::vector< std::vector
< double > > _x2Pad
std::vector< std::vector
< double > > _x3Pad
std::vector< std::vector
< double > > _y0Pad
std::vector< std::vector
< double > > _y1Pad
std::vector< std::vector
< double > > _y2Pad
std::vector< std::vector
< double > > _y3Pad
bool _elecSetupDone
bool _geomSetupDone
Detailed Description
Definition at line 11 of file geomManager.hh.
Constructor & Destructor Documentation
femGeomManager::femGeomManager (void)
Definition at line 11 of file geomManager.cc.
{ _elecSetupDone = false; _geomSetupDone = false; }
femGeomManager::~femGeomManager (void)
Definition at line 12 of file geomManager.cc.
{ }
femGeomManager::femGeomManager (const femGeomManager & geo)
Definition at line 14 of file geomManager.cc.
References _elecSetupDone, _geomSetupDone, _iAsic, _iFec, _iPad, _iPadInAsic, _iPadMax, _iPadMin, _jPad, _jPadMax, _jPadMin, _x0Pad, _x1Pad, _x2Pad, _x3Pad, _y0Pad, _y1Pad, _y2Pad, and _y3Pad.
{
  _elecSetupDone = geo._elecSetupDone;
  _geomSetupDone = geo._geomSetupDone;
  _iPadMin = geo._iPadMin;  _jPadMin = geo._jPadMin;
  _iPadMax = geo._iPadMax;  _jPadMax = geo._jPadMax;
  _iPad  = geo._iPad;
  _jPad  = geo._jPad;
  _iAsic = geo._iAsic;
  _iFec  = geo._iFec;
  _iPadInAsic  = geo._iPadInAsic;
  _x0Pad = geo._x0Pad;   _x1Pad = geo._x1Pad;   _x2Pad = geo._x2Pad;   _x3Pad = geo._x3Pad;
  _y0Pad = geo._y0Pad;   _y1Pad = geo._y1Pad;   _y2Pad = geo._y2Pad;   _y3Pad = geo._y3Pad;
}
Member Function Documentation
int femGeomManager::asic (int iPhysCh) const
pad column from phys channel
Definition at line 181 of file geomManager.cc.
{
  if( iPhysCh >= 0 && iPhysCh < int(_iPad.size()) ) return _iAsic[iPhysCh];
  return -1;
}
void femGeomManager::dumpToRootFile (TFile * f, const std::string & geoTreeName = "femGeomTree")
return double[] for root
i/o to store geom in a root file
Definition at line 300 of file geomManager.cc.
Referenced by main().
{
  if( f == 0 || !f->IsOpen() || f->IsZombie() ) {
    cerr << " ERROR[ femGeomManager::dumpToRootFile ] output root file is not opened properly... " << endl;
    return;
  }
  f->cd();
  TTree *t = new TTree(treeName.c_str(),"fem geometrye" );
  t->Branch("iPad" , &_iPad  );
  t->Branch("jPad" , &_jPad  );
  t->Branch("iAsic", &_iAsic );
  t->Branch("iFec" , &_iFec  );
  t->Branch("iPadInAsic" , &_iPadInAsic  );
  t->Branch("x0Pad" , &_x0Pad  );
  t->Branch("x1Pad" , &_x1Pad  );
  t->Branch("x2Pad" , &_x2Pad  );
  t->Branch("x3Pad" , &_x3Pad  );
  t->Branch("y0Pad" , &_y0Pad  );
  t->Branch("y1Pad" , &_y1Pad  );
  t->Branch("y2Pad" , &_y2Pad  );
  t->Branch("y3Pad" , &_y3Pad  );
  t->Branch("iPadMin", &_iPadMin );
  t->Branch("jPadMin", &_jPadMin );
  t->Branch("iPadMax", &_iPadMax );
  t->Branch("jPadMax", &_jPadMax );
  t->Fill();
  t->Write(treeName.c_str(),TObject::kOverwrite);
}
int femGeomManager::fec (int iPhysCh) const
Definition at line 186 of file geomManager.cc.
{
  if( iPhysCh >= 0 && iPhysCh < int(_iPad.size()) ) return _iFec[iPhysCh];
  return -1;
}
void femGeomManager::initFromRootFile (std::string rootFileName, const std::string & treeName = "femGeomTree")
Definition at line 332 of file geomManager.cc.
References f.
Referenced by tpcPedestal::calcPedestals(), tpcPedestal::dummyPedestals(), and main().
{
  TFile f(rootFileName.c_str(),"read");
  if( !f.IsOpen() || f.IsZombie() ) {
    cerr << " ERROR[ femGeomManager::initFromRootFile ] input root file is not opened properly... " << endl;
    return;
  }
  f.cd();
  TTree *t = (TTree*) f.Get(treeName.c_str());
  vector<int> *tmp_iPad(0), *tmp_jPad(0), *tmp_iAsic(0), *tmp_iFec(0), *tmp_iPadInAsic(0);
  std::vector<std::vector<double> > *tmp_x0Pad(0), *tmp_x1Pad(0), *tmp_x2Pad(0), *tmp_x3Pad(0);
  std::vector<std::vector<double> > *tmp_y0Pad(0), *tmp_y1Pad(0), *tmp_y2Pad(0), *tmp_y3Pad(0);
  t->SetBranchAddress("iPad" , &tmp_iPad  );
  t->SetBranchAddress("jPad" , &tmp_jPad  );
  t->SetBranchAddress("iAsic", &tmp_iAsic );
  t->SetBranchAddress("iFec" , &tmp_iFec  );
  t->SetBranchAddress("iPadInAsic" , &tmp_iPadInAsic  );
  t->SetBranchAddress("x0Pad" , &tmp_x0Pad  );
  t->SetBranchAddress("x1Pad" , &tmp_x1Pad  );
  t->SetBranchAddress("x2Pad" , &tmp_x2Pad  );
  t->SetBranchAddress("x3Pad" , &tmp_x3Pad  );
  t->SetBranchAddress("y0Pad" , &tmp_y0Pad  );
  t->SetBranchAddress("y1Pad" , &tmp_y1Pad  );
  t->SetBranchAddress("y2Pad" , &tmp_y2Pad  );
  t->SetBranchAddress("y3Pad" , &tmp_y3Pad  );
  t->SetBranchAddress("iPadMin", &_iPadMin );
  t->SetBranchAddress("jPadMin", &_jPadMin );
  t->SetBranchAddress("iPadMax", &_iPadMax );
  t->SetBranchAddress("jPadMax", &_jPadMax );
  //  t->Print();
  t->GetEntry(0);
  _iPad  = *tmp_iPad;
  _jPad  = *tmp_jPad;
  _iAsic = *tmp_iAsic;
  _iFec  = *tmp_iFec;
  _iPadInAsic  = *tmp_iPadInAsic;
  _x0Pad = *tmp_x0Pad;   _x1Pad = *tmp_x1Pad;   _x2Pad = *tmp_x2Pad;   _x3Pad = *tmp_x3Pad;
  _y0Pad = *tmp_y0Pad;   _y1Pad = *tmp_y1Pad;   _y2Pad = *tmp_y2Pad;   _y3Pad = *tmp_y3Pad;
  _elecSetupDone = true;
  _geomSetupDone = true;
  f.Close();
}
int femGeomManager::iPad (int iPhysCh) const
Definition at line 170 of file geomManager.cc.
Referenced by tpcPedestal::calcPedestals(), tpcPedestal::dummyPedestals(), xPad(), and yPad().
{
  if( iPhysCh >= 0 && iPhysCh < int(_iPad.size()) ) return _iPad[iPhysCh];
  return -1;
}
int femGeomManager::iPadMax (void) const [inline]
Definition at line 36 of file geomManager.hh.
References _iPadMax.
{ return _iPadMax;}
int femGeomManager::iPadMin (void) const [inline]
Definition at line 35 of file geomManager.hh.
References _iPadMin.
{ return _iPadMin;}
int femGeomManager::jPad (int iPhysCh) const
pad row from phys channel
Definition at line 175 of file geomManager.cc.
Referenced by tpcPedestal::calcPedestals(), tpcPedestal::dummyPedestals(), xPad(), and yPad().
{
  if( iPhysCh >= 0 && iPhysCh < int(_iPad.size()) ) return _jPad[iPhysCh];
  return -1;
}
int femGeomManager::jPadMax (void) const [inline]
Definition at line 38 of file geomManager.hh.
References _jPadMax.
{ return _jPadMax;}
int femGeomManager::jPadMin (void) const [inline]
Definition at line 37 of file geomManager.hh.
References _jPadMin.
{ return _jPadMin;}
int femGeomManager::nCol (void) const [inline]
Definition at line 25 of file geomManager.hh.
References _jPadMax, and _jPadMin.
Referenced by tpcPedestal::calcPedestals(), tpcPedestal::dummyPedestals(), and femGeomViewer::init().
{ return _jPadMax - _jPadMin + 1; }
int femGeomManager::nPad (void) const [inline]
Definition at line 23 of file geomManager.hh.
References _iPad.
Referenced by tpcPedestal::calcPedestals(), and tpcPedestal::dummyPedestals().
{ return _iPad.size(); }
int femGeomManager::nRow (void) const [inline]
Definition at line 24 of file geomManager.hh.
References _iPadMax, and _iPadMin.
Referenced by tpcPedestal::calcPedestals(), tpcPedestal::dummyPedestals(), and femGeomViewer::init().
{ return _iPadMax - _iPadMin + 1; }
femGeomManager & femGeomManager::operator= (const femGeomManager & geo)
Definition at line 34 of file geomManager.cc.
References _elecSetupDone, _geomSetupDone, _iAsic, _iFec, _iPad, _iPadInAsic, _iPadMax, _iPadMin, _jPad, _jPadMax, _jPadMin, _x0Pad, _x1Pad, _x2Pad, _x3Pad, _y0Pad, _y1Pad, _y2Pad, and _y3Pad.
{
  _elecSetupDone = geo._elecSetupDone;
  _geomSetupDone = geo._geomSetupDone;
  _iPadMin = geo._iPadMin;  _jPadMin = geo._jPadMin;
  _iPadMax = geo._iPadMax;  _jPadMax = geo._jPadMax;
  _iPad  = geo._iPad;
  _jPad  = geo._jPad;
  _iAsic = geo._iAsic;
  _iFec  = geo._iFec;
  _iPadInAsic  = geo._iPadInAsic;
  _x0Pad = geo._x0Pad;   _x1Pad = geo._x1Pad;   _x2Pad = geo._x2Pad;   _x3Pad = geo._x3Pad;
  _y0Pad = geo._y0Pad;   _y1Pad = geo._y1Pad;   _y2Pad = geo._y2Pad;   _y3Pad = geo._y3Pad;
  return *this;
}
int femGeomManager::padInAsic (int iPhysCh) const
Definition at line 191 of file geomManager.cc.
{
  if( iPhysCh >= 0 && iPhysCh < int(_iPad.size()) ) return _iPadInAsic[iPhysCh];
  return -1;
}
void femGeomManager::readElectronic (void) [private]
tmp variables
then copy the ordered map to a vector to make the access faster...
Definition at line 55 of file geomManager.cc.
References asic_fec, column, kPhysChanPerAsic, pad, and row.
Referenced by setElectronicMap().
{
  _iPadMin = -1;
  _iPadMax = -1;
  _jPadMin = -1;
  _jPadMax = -1;
  int kPhysChanPerAsic = 72;
 /// tmp variables
  map<int,int> iPad, jPad;
  map<int,int> iAsic,iFec,iPadInAsic;
  // get mapping
  int iASIC=0;
  int iFEC=0;
  ifstream input(_elecMap.c_str());
  while ( input.good() && !input.eof() ) {
    string line;
    getline(input,line,'\n');
    istringstream parse(line);
    int asic_fec (-1), row(-1), column(-1), pad(-1);
    int ipad(-1);
    parse >> asic_fec >> row >> column >> pad;
    //    cout << " asic: " << asic_fec  << " row: " << row << " column: " << column << " pad: " << pad << endl;
    if( asic_fec == -1 || row == -1 || column == -1 ) continue;
    if      (column>=60) iFEC=5;
    else if (column>=48) iFEC=4;
    else if (column>=36) iFEC=3;
    else if (column>=24) iFEC=2;
    else if (column>=12) iFEC=1;
    else                 iFEC=0;
    // Comment by YHS
    //
    // The Map : (Row, Col) --> PhysChan
    //
    // NOTE: PhysChan is the most important one,
    //       which is the one that we can get from the ACQ data file, and
    //       which should be used to find (row, col) of the pad from it !
    //
    //
    //
    // NOTE : 2 pads denoted by -1 are being used for HV.
    //        This results in two missing channel numbers : 72 and 73 !!!
    //
    iASIC = asic_fec + 4*iFEC;
    if  ( pad != -1 ) {
      ipad = pad + kPhysChanPerAsic*iASIC;
    }
    else {
//       stringstream iss;
//       iss << "  Pad at row,col: " << setw(2) << row << "," << setw(2) << column
//           << " is for HV :  ";
//       // NOTE: Modify this when mapping is being changed !
//       //
// //      if (column == 65) iPAD[i] = 72;
// //      if (column == 64) iPAD[i] = 73;
//       iss << "Channel ID is assinged manually to " << iPAD[i];
      //  missingChannelInfo.push_back( iss.str() );
    }
    if( _iPadMin == -1 ) _iPadMin = row;
    if( _iPadMax == -1 ) _iPadMax = row;
    if( _jPadMin == -1 ) _jPadMin = column;
    if( _jPadMax == -1 ) _jPadMax = column;
    if( row < _iPadMin ) _iPadMin = row;
    if( row > _iPadMax ) _iPadMax = row;
    if( column < _jPadMin ) _jPadMin = column;
    if( column > _jPadMax ) _jPadMax = column;
    //    int kMaxCols = 72;
    iPad.insert(  make_pair(ipad,row)      );
    jPad.insert(  make_pair(ipad,column)   );
    iAsic.insert( make_pair(ipad,iASIC)    );
    iFec .insert( make_pair(ipad,iFEC)     );
    iPadInAsic.insert( make_pair(ipad,pad) );
    //    _chPad.insert( make_pair(ipad,column + row * kMaxCols)   );
  }
  /// then copy the ordered map to a vector to make the access faster...
  _iPad.resize(  iPad.size() );
  _jPad.resize(  jPad.size() );
  _iAsic.resize( iAsic.size() );
  _iFec.resize(  iFec.size() );
  _iPadInAsic.resize(  iPadInAsic.size() );
  map<int,int>::const_iterator it;
  for( it = iPad.begin() ; it != iPad.end() ; ++it ) _iPad [it->first] = it->second;
  for( it = jPad.begin() ; it != jPad.end() ; ++it ) _jPad [it->first] = it->second;
  for( it = iAsic.begin(); it != iAsic.end(); ++it ) _iAsic[it->first] = it->second;
  for( it = iFec.begin() ; it != iFec.end() ; ++it ) _iFec [it->first] = it->second;
  for( it = iPadInAsic.begin() ; it != iPadInAsic.end() ; ++it ) _iPadInAsic[it->first] = it->second;
  input.close();
  _elecSetupDone = true;
  cout << " ====> Added " << _iPad.size() << " channels" << endl;
}
int femGeomManager::readGeometry (void) [private]
Definition at line 210 of file geomManager.cc.
References row.
Referenced by setGeometryMap().
{
  if(  !_elecSetupDone ) {
    cerr << "ERROR femGeomManager::readGeomtry(...): need to decode the electronic map before decoding the geometry! bailing out..." << endl;
    return -1;
  }
  ifstream padGeomFile(_geomMap.c_str());
  if ( !padGeomFile ) {
    cerr << "ERROR femGeomManager::readGeomtry(...): Can't open file : " << _geomMap << endl;
    return -1;
  }
  char   varName[20];
  double width;
  double ymin, ymax;
  padGeomFile >> varName >> width;  // half width of the pad panel
  padGeomFile >> varName >> ymin;
  padGeomFile >> varName >> ymax;
  // tpcPanelWidth  = 2. * width;         // total width  of the pad array
  // tpcPanelHeight = ymax - ymin;        // total height of the pad array
  cout << " ===== Decoding geometry ======== " << endl;
  cout << "FEM Pad Panel: w , ymin, ymax = "
       << width << ", " << ymin << ", " << ymax << endl;
  unsigned nRow = _iPadMax - _iPadMin + 1;
  unsigned nCol = _jPadMax - _jPadMin + 1;
  vector<vector<double> > x0_v(nRow),y0_v(nRow);
  vector<vector<double> > x1_v(nRow),y1_v(nRow);
  vector<vector<double> > x2_v(nRow),y2_v(nRow);
  vector<vector<double> > x3_v(nRow),y3_v(nRow);
  for( unsigned ix = 0 ; ix < x0_v.size(); ix++ ) {
    x0_v[ix].resize(nCol,-1.);   y0_v[ix].resize(nCol,-1.);
    x1_v[ix].resize(nCol,-1.);   y1_v[ix].resize(nCol,-1.);
    x2_v[ix].resize(nCol,-1.);   y2_v[ix].resize(nCol,-1.);
    x3_v[ix].resize(nCol,-1.);   y3_v[ix].resize(nCol,-1.);
  }
  while ( padGeomFile.good() && !padGeomFile.eof() ) {
    int row, col;
    double x0, y0, x1, y1, x2, y2, x3, y3;
    padGeomFile >> row >> col
                >> x0 >> y0 >> x1 >> y1 >> x2 >> y2 >> x3 >> y3;
    x0_v[row][col] = x0;  y0_v[row][col] = y0;
    x1_v[row][col] = x1;  y1_v[row][col] = y1;
    x2_v[row][col] = x2;  y2_v[row][col] = y2;
    x3_v[row][col] = x3;  y3_v[row][col] = y3;
  }
  padGeomFile.close();
  _x0Pad = x0_v;  _y0Pad = y0_v;
  _x1Pad = x1_v;  _y1Pad = y1_v;
  _x2Pad = x2_v;  _y2Pad = y2_v;
  _x3Pad = x3_v;  _y3Pad = y3_v;
  //  setGeo2DVisual();
  _geomSetupDone = true;
  return 0;
}
void femGeomManager::setElectronicMap (std::string map) [inline]
init geometry from flat ascii files
Definition at line 20 of file geomManager.hh.
References _elecMap, and readElectronic().
Referenced by main().
{ _elecMap = map; readElectronic(); }
void femGeomManager::setGeometryMap (std::string map) [inline]
Definition at line 21 of file geomManager.hh.
References _geomMap, and readGeometry().
Referenced by main().
{ _geomMap = map; readGeometry()  ; }
double femGeomManager::xPad (int i, int j) const
Definition at line 201 of file geomManager.cc.
Referenced by yPad().
{
  return 0.25 *( _x0Pad[i][j] + _x1Pad[i][j] + _x2Pad[i][j] + _x3Pad[i][j] );
}
double femGeomManager::xPad (int iPhysCh) const [inline]
Definition at line 45 of file geomManager.hh.
References iPad(), jPad(), and xPad().
Referenced by xPad().
{ return xPad(iPad(iPhysCh),jPad(iPhysCh)); }
double femGeomManager::xPadCoord (int i, int j, int k) const
Definition at line 277 of file geomManager.cc.
Referenced by femGeomViewer::init().
{
  if( k == 0 ) return _x0Pad[i][j];
  if( k == 1 ) return _x1Pad[i][j];
  if( k == 2 ) return _x2Pad[i][j];
  if( k == 3 ) return _x3Pad[i][j];
  return -1;
}
double femGeomManager::yPad (int i, int j) const
Definition at line 206 of file geomManager.cc.
{
  return 0.25 *( _y0Pad[i][j] + _y1Pad[i][j] + _y2Pad[i][j] + _y3Pad[i][j] );
}
double femGeomManager::yPad (int iPhysCh) const [inline]
Definition at line 46 of file geomManager.hh.
References iPad(), jPad(), and xPad().
{ return xPad(iPad(iPhysCh),jPad(iPhysCh)); }
double femGeomManager::yPadCoord (int i, int j, int k) const
return double[] for root
Definition at line 287 of file geomManager.cc.
Referenced by femGeomViewer::init().
{
  if( k == 0 ) return _y0Pad[i][j];
  if( k == 1 ) return _y1Pad[i][j];
  if( k == 2 ) return _y2Pad[i][j];
  if( k == 3 ) return _y3Pad[i][j];
  return -1;
}
Member Data Documentation
std::string femGeomManager::_elecMap [private]
Definition at line 60 of file geomManager.hh.
Referenced by setElectronicMap().
bool femGeomManager::_elecSetupDone [private]
Definition at line 70 of file geomManager.hh.
Referenced by femGeomManager(), and operator=().
std::string femGeomManager::_geomMap [private]
Definition at line 61 of file geomManager.hh.
Referenced by setGeometryMap().
bool femGeomManager::_geomSetupDone [private]
Definition at line 71 of file geomManager.hh.
Referenced by femGeomManager(), and operator=().
std::vector<int> femGeomManager::_iAsic [private]
Definition at line 65 of file geomManager.hh.
Referenced by femGeomManager(), and operator=().
std::vector<int> femGeomManager::_iFec [private]
Definition at line 65 of file geomManager.hh.
Referenced by femGeomManager(), and operator=().
std::vector<int> femGeomManager::_iPad [private]
Definition at line 64 of file geomManager.hh.
Referenced by femGeomManager(), nPad(), and operator=().
std::vector<int> femGeomManager::_iPadInAsic [private]
Definition at line 65 of file geomManager.hh.
Referenced by femGeomManager(), and operator=().
int femGeomManager::_iPadMax [private]
Definition at line 62 of file geomManager.hh.
Referenced by femGeomManager(), iPadMax(), nRow(), and operator=().
int femGeomManager::_iPadMin [private]
Definition at line 62 of file geomManager.hh.
Referenced by femGeomManager(), iPadMin(), nRow(), and operator=().
std::vector<int> femGeomManager::_jPad [private]
Definition at line 64 of file geomManager.hh.
Referenced by femGeomManager(), and operator=().
int femGeomManager::_jPadMax [private]
Definition at line 62 of file geomManager.hh.
Referenced by femGeomManager(), jPadMax(), nCol(), and operator=().
int femGeomManager::_jPadMin [private]
Definition at line 62 of file geomManager.hh.
Referenced by femGeomManager(), jPadMin(), nCol(), and operator=().
std::vector<std::vector<double> > femGeomManager::_x0Pad [private]
electronic path
Definition at line 67 of file geomManager.hh.
Referenced by femGeomManager(), and operator=().
std::vector<std::vector<double> > femGeomManager::_x1Pad [private]
Definition at line 67 of file geomManager.hh.
Referenced by femGeomManager(), and operator=().
std::vector<std::vector<double> > femGeomManager::_x2Pad [private]
Definition at line 67 of file geomManager.hh.
Referenced by femGeomManager(), and operator=().
std::vector<std::vector<double> > femGeomManager::_x3Pad [private]
Definition at line 67 of file geomManager.hh.
Referenced by femGeomManager(), and operator=().
std::vector<std::vector<double> > femGeomManager::_y0Pad [private]
Definition at line 68 of file geomManager.hh.
Referenced by femGeomManager(), and operator=().
std::vector<std::vector<double> > femGeomManager::_y1Pad [private]
Definition at line 68 of file geomManager.hh.
Referenced by femGeomManager(), and operator=().
std::vector<std::vector<double> > femGeomManager::_y2Pad [private]
Definition at line 68 of file geomManager.hh.
Referenced by femGeomManager(), and operator=().
std::vector<std::vector<double> > femGeomManager::_y3Pad [private]
Definition at line 68 of file geomManager.hh.
Referenced by femGeomManager(), and operator=().
The documentation for this class was generated from the following files:
/home/tuchming/data/saclay1_e6430/miniTPC/code/DataWriter/interface/geomManager.hh
/home/tuchming/data/saclay1_e6430/miniTPC/code/DataWriter/src/geomManager.cc