testcodeTPC: femGeomViewer Class Reference
femGeomViewer Class Reference
#include <geomManager.hh>
Public Member Functions
femGeomViewer (std::string rootName, const femGeomManager &geo)
femGeomViewer (void)
bool init (std::string rootName, const femGeomManager &geo)
init is actually done only if the viewer is not setup otherwise this is really long
void reset ()
void setBinContent (int iPad, int jPad, int tPad, double val)
void drawXY (std::string options="")
void drawXT (std::string options="")
void drawTY (std::string options="")
void drawCopyXY (std::string options="")
void drawCopyXT (std::string options="")
void drawCopyTY (std::string options="")
void setMinMax (double min, double max)
std::auto_ptr< TH2Poly > getHistoXY (void)
accessors if the user want to fill the histo himself...
int getBinNumber (int iPad, int jPad) const
Private Attributes
std::auto_ptr< TH2Poly > _XYviewer
use smart pointer so it owns the pointer;
std::auto_ptr< TH2F > _XTviewer
std::auto_ptr< TH2F > _TYviewer
std::vector< std::vector< int > > _binNumber2D
Detailed Description
Definition at line 82 of file geomManager.hh.
Constructor & Destructor Documentation
femGeomViewer::femGeomViewer (std::string rootName, const femGeomManager & geo) [inline]
Definition at line 84 of file geomManager.hh.
References init().
{ init(rootName,geo); }
femGeomViewer::femGeomViewer (void) [inline]
Definition at line 85 of file geomManager.hh.
: _XYviewer(0), _XTviewer(0), _TYviewer(0) {}
Member Function Documentation
void femGeomViewer::drawCopyTY (std::string options = "")
Definition at line 456 of file geomManager.cc.
{ _TYviewer->DrawCopy(option.c_str()); }
void femGeomViewer::drawCopyXT (std::string options = "")
Definition at line 455 of file geomManager.cc.
{ _XTviewer->DrawCopy(option.c_str()); }
void femGeomViewer::drawCopyXY (std::string options = "")
Definition at line 454 of file geomManager.cc.
Referenced by tpcPedestal::calcPedestals().
{ _XYviewer->DrawCopy(option.c_str()); }
void femGeomViewer::drawTY (std::string options = "")
Definition at line 452 of file geomManager.cc.
{ _TYviewer->Draw(option.c_str()); }
void femGeomViewer::drawXT (std::string options = "")
Definition at line 451 of file geomManager.cc.
{ _XTviewer->Draw(option.c_str()); }
void femGeomViewer::drawXY (std::string options = "")
Definition at line 450 of file geomManager.cc.
{ _XYviewer->Draw(option.c_str()); }
int femGeomViewer::getBinNumber (int iPad, int jPad) const
Definition at line 470 of file geomManager.cc.
{ return _binNumber2D[iPad][jPad]; }
std::auto_ptr<TH2Poly> femGeomViewer::getHistoXY (void) [inline]
accessors if the user want to fill the histo himself...
Definition at line 103 of file geomManager.hh.
References _XYviewer.
{ return _XYviewer; }
bool femGeomViewer::init (std::string rootName, const femGeomManager & geo)
init is actually done only if the viewer is not setup otherwise this is really long
XY view
XT view
Definition at line 383 of file geomManager.cc.
References femGeomManager::nCol(), femGeomManager::nRow(), femGeomManager::xPadCoord(), and femGeomManager::yPadCoord().
Referenced by femGeomViewer().
{
  reset();
  if( _XYviewer.get() ) return false;
  double xmin = +9999;
  double xmax = -9999;
  double ymin = +9999;
  double ymax = -9999;
  /// XY view
  _XYviewer.reset( new TH2Poly() );
  _XYviewer->SetName( rootName.c_str() );
  _XYviewer->SetTitle(rootName.c_str() );
  _binNumber2D.resize(geo.nRow());
  for( int ir = 0 ; ir < geo.nRow(); ir++ ) {
    _binNumber2D[ir].resize(geo.nCol());
    for( int ic = 0 ; ic < geo.nCol(); ic++ ) {
      double px[4];
      double py[4];
      for( int i = 0 ; i < 4; i++ ) {
          px[i] = geo.xPadCoord(ir,ic, i);
          py[i] = geo.yPadCoord(ir,ic, i);
          if( px[i] < xmin ) xmin = px[i];
          if( px[i] > xmax ) xmax = px[i];
          if( py[i] < ymin ) ymin = py[i];
          if( py[i] > ymax ) ymax = py[i];
      }
      _binNumber2D[ir][ic] = _XYviewer->AddBin( 4, px,py);
    }
  }
  _XYviewer->GetXaxis()->SetTitle("x [mm]"); _XYviewer->GetXaxis()->CenterTitle();
  _XYviewer->GetYaxis()->SetTitle("y [mm]"); _XYviewer->GetYaxis()->CenterTitle();
  /// XT view
  double tmin = 49.5;
  double tmax = 199.5;
  int nbin = 25;
  _XTviewer.reset( new TH2F( (rootName + "XT").c_str(), (rootName + "XT").c_str(), geo.nCol(),xmin,xmax, nbin,tmin,tmax ) );
  _TYviewer.reset( new TH2F( (rootName + "TY").c_str(), (rootName + "TY").c_str(), nbin,tmin,tmax, geo.nRow(),ymin,ymax ) );
  _XTviewer->GetXaxis()->SetTitle("x [mm]"      ); _XTviewer->GetXaxis()->CenterTitle();
  _XTviewer->GetYaxis()->SetTitle("t [#samples]"); _XTviewer->GetYaxis()->CenterTitle();
  _TYviewer->GetXaxis()->SetTitle("t [#samples]"); _TYviewer->GetXaxis()->CenterTitle();
  _TYviewer->GetYaxis()->SetTitle("y [mm]"      ); _TYviewer->GetYaxis()->CenterTitle();
  return true;
}
void femGeomViewer::reset ()
Definition at line 433 of file geomManager.cc.
{
  if( _XYviewer.get() ) _XYviewer->Reset("");
  if( _XTviewer.get() ) _XTviewer->Reset();
  if( _TYviewer.get() ) _TYviewer->Reset();
}
void femGeomViewer::setBinContent (int iPad, int jPad, int tPad, double val)
Definition at line 440 of file geomManager.cc.
References x, and y.
Referenced by tpcPedestal::calcPedestals().
{
  _XYviewer->SetBinContent( _binNumber2D[iPad][jPad],val );
  //  int tbin = _XTviewer->GetYaxis()->FindBin( tPad );
  double x = _XTviewer->GetXaxis()->GetBinCenter( jPad+1 );
  double y = _TYviewer->GetYaxis()->GetBinCenter( iPad+1 );
  _XTviewer->Fill( x, tPad, val );
  _TYviewer->Fill( tPad, y, val );
}
void femGeomViewer::setMinMax (double min, double max)
Definition at line 458 of file geomManager.cc.
Referenced by tpcPedestal::calcPedestals().
{
  _XYviewer->SetMinimum(min);
  _XYviewer->SetMaximum(max);
  _XTviewer->SetMinimum(min);
  _XTviewer->SetMaximum(max);
  _TYviewer->SetMinimum(min);
  _TYviewer->SetMaximum(max);
}
Member Data Documentation
std::vector<std::vector<int> > femGeomViewer::_binNumber2D [private]
Definition at line 112 of file geomManager.hh.
std::auto_ptr<TH2F> femGeomViewer::_TYviewer [private]
Definition at line 110 of file geomManager.hh.
std::auto_ptr<TH2F> femGeomViewer::_XTviewer [private]
Definition at line 109 of file geomManager.hh.
std::auto_ptr<TH2Poly> femGeomViewer::_XYviewer [private]
use smart pointer so it owns the pointer;
Definition at line 108 of file geomManager.hh.
Referenced by getHistoXY().
The documentation for this class was generated from the following files:
/home/tuchming/data/saclay1_e6430/miniTPC/code/DataWriter/interface/geomManager.hh
/home/tuchming/data/saclay1_e6430/miniTPC/code/DataWriter/src/geomManager.cc