testcodeTPC: ROOT Namespace Reference
ROOT Namespace Reference
Namespaces
namespace Shadow
Functions
void tpcXmlConfig_ShowMembers (void *obj, TMemberInspector &R__insp)
static void tpcXmlConfig_Dictionary ()
static void * new_tpcXmlConfig (void *p=0)
static void * newArray_tpcXmlConfig (Long_t size, void *p)
static void delete_tpcXmlConfig (void *p)
static void deleteArray_tpcXmlConfig (void *p)
static void destruct_tpcXmlConfig (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const ::tpcXmlConfig *)
TGenericClassInfo * GenerateInitInstance (const ::tpcXmlConfig *)
::ROOT::TGenericClassInfo * _R__UNIQUE_ (Init) = GenerateInitInstanceLocal((const vector<double>*)0x0)
R__UseDummy (_R__UNIQUE_(Init))
void vectorlEdoublegR_ShowMembers (void *obj, TMemberInspector &R__insp)
static void vectorlEdoublegR_Dictionary ()
static void * new_vectorlEdoublegR (void *p=0)
static void * newArray_vectorlEdoublegR (Long_t size, void *p)
static void delete_vectorlEdoublegR (void *p)
static void deleteArray_vectorlEdoublegR (void *p)
static void destruct_vectorlEdoublegR (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const vector< double > *)
void vectorlEintgR_ShowMembers (void *obj, TMemberInspector &R__insp)
static void vectorlEintgR_Dictionary ()
static void * new_vectorlEintgR (void *p=0)
static void * newArray_vectorlEintgR (Long_t size, void *p)
static void delete_vectorlEintgR (void *p)
static void deleteArray_vectorlEintgR (void *p)
static void destruct_vectorlEintgR (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const vector< int > *)
void vectorlEvectorlEdoublegRsPgR_ShowMembers (void *obj, TMemberInspector &R__insp)
static void vectorlEvectorlEdoublegRsPgR_Dictionary ()
static void * new_vectorlEvectorlEdoublegRsPgR (void *p=0)
static void * newArray_vectorlEvectorlEdoublegRsPgR (Long_t size, void *p)
static void delete_vectorlEvectorlEdoublegRsPgR (void *p)
static void deleteArray_vectorlEvectorlEdoublegRsPgR (void *p)
static void destruct_vectorlEvectorlEdoublegRsPgR (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const vector< vector< double > > *)
void vectorlEvectorlEintgRsPgR_ShowMembers (void *obj, TMemberInspector &R__insp)
static void vectorlEvectorlEintgRsPgR_Dictionary ()
static void * new_vectorlEvectorlEintgRsPgR (void *p=0)
static void * newArray_vectorlEvectorlEintgRsPgR (Long_t size, void *p)
static void delete_vectorlEvectorlEintgRsPgR (void *p)
static void deleteArray_vectorlEvectorlEintgRsPgR (void *p)
static void destruct_vectorlEvectorlEintgRsPgR (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const vector< vector< int > > *)
Function Documentation
ROOT::TGenericClassInfo * ROOT::_R__UNIQUE_ (Init) = GenerateInitInstanceLocal((const vector<double>*)0x0) [static]
static void ROOT::delete_tpcXmlConfig (void * p) [static]
Definition at line 90 of file dict_interface.cc.
Referenced by GenerateInitInstanceLocal().
{
      delete ((::tpcXmlConfig*)p);
   }
static void ROOT::delete_vectorlEdoublegR (void * p) [static]
Definition at line 148 of file dict_interface.cc.
Referenced by GenerateInitInstanceLocal().
{
      delete ((vector<double>*)p);
   }
static void ROOT::delete_vectorlEintgR (void * p) [static]
Definition at line 206 of file dict_interface.cc.
Referenced by GenerateInitInstanceLocal().
{
      delete ((vector<int>*)p);
   }
static void ROOT::delete_vectorlEvectorlEdoublegRsPgR (void * p) [static]
Definition at line 264 of file dict_interface.cc.
Referenced by GenerateInitInstanceLocal().
{
      delete ((vector<vector<double> >*)p);
   }
static void ROOT::delete_vectorlEvectorlEintgRsPgR (void * p) [static]
Definition at line 322 of file dict_interface.cc.
Referenced by GenerateInitInstanceLocal().
{
      delete ((vector<vector<int> >*)p);
   }
static void ROOT::deleteArray_tpcXmlConfig (void * p) [static]
Definition at line 93 of file dict_interface.cc.
Referenced by GenerateInitInstanceLocal().
{
      delete [] ((::tpcXmlConfig*)p);
   }
static void ROOT::deleteArray_vectorlEdoublegR (void * p) [static]
Definition at line 151 of file dict_interface.cc.
Referenced by GenerateInitInstanceLocal().
{
      delete [] ((vector<double>*)p);
   }
static void ROOT::deleteArray_vectorlEintgR (void * p) [static]
Definition at line 209 of file dict_interface.cc.
Referenced by GenerateInitInstanceLocal().
{
      delete [] ((vector<int>*)p);
   }
static void ROOT::deleteArray_vectorlEvectorlEdoublegRsPgR (void * p) [static]
Definition at line 267 of file dict_interface.cc.
Referenced by GenerateInitInstanceLocal().
{
      delete [] ((vector<vector<double> >*)p);
   }
static void ROOT::deleteArray_vectorlEvectorlEintgRsPgR (void * p) [static]
Definition at line 325 of file dict_interface.cc.
Referenced by GenerateInitInstanceLocal().
{
      delete [] ((vector<vector<int> >*)p);
   }
static void ROOT::destruct_tpcXmlConfig (void * p) [static]
Definition at line 96 of file dict_interface.cc.
Referenced by GenerateInitInstanceLocal().
{
      typedef ::tpcXmlConfig current_t;
      ((current_t*)p)->~current_t();
   }
static void ROOT::destruct_vectorlEdoublegR (void * p) [static]
Definition at line 154 of file dict_interface.cc.
Referenced by GenerateInitInstanceLocal().
{
      typedef vector<double> current_t;
      ((current_t*)p)->~current_t();
   }
static void ROOT::destruct_vectorlEintgR (void * p) [static]
Definition at line 212 of file dict_interface.cc.
Referenced by GenerateInitInstanceLocal().
{
      typedef vector<int> current_t;
      ((current_t*)p)->~current_t();
   }
static void ROOT::destruct_vectorlEvectorlEdoublegRsPgR (void * p) [static]
Definition at line 270 of file dict_interface.cc.
Referenced by GenerateInitInstanceLocal().
{
      typedef vector<vector<double> > current_t;
      ((current_t*)p)->~current_t();
   }
static void ROOT::destruct_vectorlEvectorlEintgRsPgR (void * p) [static]
Definition at line 328 of file dict_interface.cc.
Referenced by GenerateInitInstanceLocal().
{
      typedef vector<vector<int> > current_t;
      ((current_t*)p)->~current_t();
   }
TGenericClassInfo* ROOT::GenerateInitInstance (const ::tpcXmlConfig *)
Definition at line 67 of file dict_interface.cc.
References GenerateInitInstanceLocal().
   {
      return GenerateInitInstanceLocal((::tpcXmlConfig*)0);
   }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const ::tpcXmlConfig *) [static]
Definition at line 51 of file dict_interface.cc.
References delete_tpcXmlConfig(), deleteArray_tpcXmlConfig(), destruct_tpcXmlConfig(), new_tpcXmlConfig(), newArray_tpcXmlConfig(), and tpcXmlConfig_Dictionary().
Referenced by GenerateInitInstance(), tpcXmlConfig_Dictionary(), vectorlEdoublegR_Dictionary(), vectorlEintgR_Dictionary(), vectorlEvectorlEdoublegRsPgR_Dictionary(), and vectorlEvectorlEintgRsPgR_Dictionary().
   {
      ::tpcXmlConfig *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::tpcXmlConfig),0);
      static ::ROOT::TGenericClassInfo
         instance("tpcXmlConfig", "./interface/xmlReader.hh", 12,
                  typeid(::tpcXmlConfig), DefineBehavior(ptr, ptr),
                  0, &tpcXmlConfig_Dictionary, isa_proxy, 0,
                  sizeof(::tpcXmlConfig) );
      instance.SetNew(&new_tpcXmlConfig);
      instance.SetNewArray(&newArray_tpcXmlConfig);
      instance.SetDelete(&delete_tpcXmlConfig);
      instance.SetDeleteArray(&deleteArray_tpcXmlConfig);
      instance.SetDestructor(&destruct_tpcXmlConfig);
      return &instance;
   }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const vector< double > *) [static]
Definition at line 112 of file dict_interface.cc.
References delete_vectorlEdoublegR(), deleteArray_vectorlEdoublegR(), destruct_vectorlEdoublegR(), new_vectorlEdoublegR(), newArray_vectorlEdoublegR(), and vectorlEdoublegR_Dictionary().
   {
      vector<double> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<double>),0);
      static ::ROOT::TGenericClassInfo
         instance("vector<double>", -2, "vector.dll", 0,
                  typeid(vector<double>), DefineBehavior(ptr, ptr),
                  0, &vectorlEdoublegR_Dictionary, isa_proxy, 0,
                  sizeof(vector<double>) );
      instance.SetNew(&new_vectorlEdoublegR);
      instance.SetNewArray(&newArray_vectorlEdoublegR);
      instance.SetDelete(&delete_vectorlEdoublegR);
      instance.SetDeleteArray(&deleteArray_vectorlEdoublegR);
      instance.SetDestructor(&destruct_vectorlEdoublegR);
      instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<double> >()));
      return &instance;
   }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const vector< int > *) [static]
Definition at line 170 of file dict_interface.cc.
References delete_vectorlEintgR(), deleteArray_vectorlEintgR(), destruct_vectorlEintgR(), new_vectorlEintgR(), newArray_vectorlEintgR(), and vectorlEintgR_Dictionary().
   {
      vector<int> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<int>),0);
      static ::ROOT::TGenericClassInfo
         instance("vector<int>", -2, "/usr/local/cern/root_5.34.03/cint/cint/lib/prec_stl/vector", 49,
                  typeid(vector<int>), DefineBehavior(ptr, ptr),
                  0, &vectorlEintgR_Dictionary, isa_proxy, 0,
                  sizeof(vector<int>) );
      instance.SetNew(&new_vectorlEintgR);
      instance.SetNewArray(&newArray_vectorlEintgR);
      instance.SetDelete(&delete_vectorlEintgR);
      instance.SetDeleteArray(&deleteArray_vectorlEintgR);
      instance.SetDestructor(&destruct_vectorlEintgR);
      instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<int> >()));
      return &instance;
   }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const vector< vector< double > > *) [static]
Definition at line 228 of file dict_interface.cc.
References delete_vectorlEvectorlEdoublegRsPgR(), deleteArray_vectorlEvectorlEdoublegRsPgR(), destruct_vectorlEvectorlEdoublegRsPgR(), new_vectorlEvectorlEdoublegRsPgR(), newArray_vectorlEvectorlEdoublegRsPgR(), and vectorlEvectorlEdoublegRsPgR_Dictionary().
   {
      vector<vector<double> > *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<vector<double> >),0);
      static ::ROOT::TGenericClassInfo
         instance("vector<vector<double> >", -2, "/usr/local/cern/root_5.34.03/cint/cint/lib/prec_stl/vector", 49,
                  typeid(vector<vector<double> >), DefineBehavior(ptr, ptr),
                  0, &vectorlEvectorlEdoublegRsPgR_Dictionary, isa_proxy, 0,
                  sizeof(vector<vector<double> >) );
      instance.SetNew(&new_vectorlEvectorlEdoublegRsPgR);
      instance.SetNewArray(&newArray_vectorlEvectorlEdoublegRsPgR);
      instance.SetDelete(&delete_vectorlEvectorlEdoublegRsPgR);
      instance.SetDeleteArray(&deleteArray_vectorlEvectorlEdoublegRsPgR);
      instance.SetDestructor(&destruct_vectorlEvectorlEdoublegRsPgR);
      instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<vector<double> > >()));
      return &instance;
   }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const vector< vector< int > > *) [static]
Definition at line 286 of file dict_interface.cc.
References delete_vectorlEvectorlEintgRsPgR(), deleteArray_vectorlEvectorlEintgRsPgR(), destruct_vectorlEvectorlEintgRsPgR(), new_vectorlEvectorlEintgRsPgR(), newArray_vectorlEvectorlEintgRsPgR(), and vectorlEvectorlEintgRsPgR_Dictionary().
   {
      vector<vector<int> > *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<vector<int> >),0);
      static ::ROOT::TGenericClassInfo
         instance("vector<vector<int> >", -2, "/usr/local/cern/root_5.34.03/cint/cint/lib/prec_stl/vector", 49,
                  typeid(vector<vector<int> >), DefineBehavior(ptr, ptr),
                  0, &vectorlEvectorlEintgRsPgR_Dictionary, isa_proxy, 0,
                  sizeof(vector<vector<int> >) );
      instance.SetNew(&new_vectorlEvectorlEintgRsPgR);
      instance.SetNewArray(&newArray_vectorlEvectorlEintgRsPgR);
      instance.SetDelete(&delete_vectorlEvectorlEintgRsPgR);
      instance.SetDeleteArray(&deleteArray_vectorlEvectorlEintgRsPgR);
      instance.SetDestructor(&destruct_vectorlEvectorlEintgRsPgR);
      instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<vector<int> > >()));
      return &instance;
   }
static void * ROOT::new_tpcXmlConfig (void * p = 0) [static]
Definition at line 83 of file dict_interface.cc.
Referenced by GenerateInitInstanceLocal().
{
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::tpcXmlConfig : new ::tpcXmlConfig;
   }
static void * ROOT::new_vectorlEdoublegR (void * p = 0) [static]
Definition at line 141 of file dict_interface.cc.
Referenced by GenerateInitInstanceLocal().
{
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<double> : new vector<double>;
   }
static void * ROOT::new_vectorlEintgR (void * p = 0) [static]
Definition at line 199 of file dict_interface.cc.
Referenced by GenerateInitInstanceLocal().
{
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<int> : new vector<int>;
   }
static void * ROOT::new_vectorlEvectorlEdoublegRsPgR (void * p = 0) [static]
Definition at line 257 of file dict_interface.cc.
Referenced by GenerateInitInstanceLocal().
{
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<vector<double> > : new vector<vector<double> >;
   }
static void * ROOT::new_vectorlEvectorlEintgRsPgR (void * p = 0) [static]
Definition at line 315 of file dict_interface.cc.
Referenced by GenerateInitInstanceLocal().
{
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<vector<int> > : new vector<vector<int> >;
   }
static void * ROOT::newArray_tpcXmlConfig (Long_t size, void * p) [static]
Definition at line 86 of file dict_interface.cc.
Referenced by GenerateInitInstanceLocal().
{
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::tpcXmlConfig[nElements] : new ::tpcXmlConfig[nElements];
   }
static void * ROOT::newArray_vectorlEdoublegR (Long_t size, void * p) [static]
Definition at line 144 of file dict_interface.cc.
Referenced by GenerateInitInstanceLocal().
{
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<double>[nElements] : new vector<double>[nElements];
   }
static void * ROOT::newArray_vectorlEintgR (Long_t size, void * p) [static]
Definition at line 202 of file dict_interface.cc.
Referenced by GenerateInitInstanceLocal().
{
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<int>[nElements] : new vector<int>[nElements];
   }
static void * ROOT::newArray_vectorlEvectorlEdoublegRsPgR (Long_t size, void * p) [static]
Definition at line 260 of file dict_interface.cc.
Referenced by GenerateInitInstanceLocal().
{
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<vector<double> >[nElements] : new vector<vector<double> >[nElements];
   }
static void * ROOT::newArray_vectorlEvectorlEintgRsPgR (Long_t size, void * p) [static]
Definition at line 318 of file dict_interface.cc.
Referenced by GenerateInitInstanceLocal().
{
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<vector<int> >[nElements] : new vector<vector<int> >[nElements];
   }
ROOT::R__UseDummy (_R__UNIQUE_(Init))
static void ROOT::tpcXmlConfig_Dictionary () [static]
Definition at line 75 of file dict_interface.cc.
References GenerateInitInstanceLocal().
Referenced by GenerateInitInstanceLocal().
{
      ::ROOT::GenerateInitInstanceLocal((const ::tpcXmlConfig*)0x0)->GetClass();
   }
void ROOT::tpcXmlConfig_ShowMembers (void * obj, TMemberInspector & R__insp)
static void ROOT::vectorlEdoublegR_Dictionary () [static]
Definition at line 133 of file dict_interface.cc.
References GenerateInitInstanceLocal().
Referenced by GenerateInitInstanceLocal().
{
      ::ROOT::GenerateInitInstanceLocal((const vector<double>*)0x0)->GetClass();
   }
void ROOT::vectorlEdoublegR_ShowMembers (void * obj, TMemberInspector & R__insp)
static void ROOT::vectorlEintgR_Dictionary () [static]
Definition at line 191 of file dict_interface.cc.
References GenerateInitInstanceLocal().
Referenced by GenerateInitInstanceLocal().
{
      ::ROOT::GenerateInitInstanceLocal((const vector<int>*)0x0)->GetClass();
   }
void ROOT::vectorlEintgR_ShowMembers (void * obj, TMemberInspector & R__insp)
static void ROOT::vectorlEvectorlEdoublegRsPgR_Dictionary () [static]
Definition at line 249 of file dict_interface.cc.
References GenerateInitInstanceLocal().
Referenced by GenerateInitInstanceLocal().
{
      ::ROOT::GenerateInitInstanceLocal((const vector<vector<double> >*)0x0)->GetClass();
   }
void ROOT::vectorlEvectorlEdoublegRsPgR_ShowMembers (void * obj, TMemberInspector & R__insp)
static void ROOT::vectorlEvectorlEintgRsPgR_Dictionary () [static]
Definition at line 307 of file dict_interface.cc.
References GenerateInitInstanceLocal().
Referenced by GenerateInitInstanceLocal().
{
      ::ROOT::GenerateInitInstanceLocal((const vector<vector<int> >*)0x0)->GetClass();
   }
void ROOT::vectorlEvectorlEintgRsPgR_ShowMembers (void * obj, TMemberInspector & R__insp)